# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_remove_complaint_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/', verbose_name='Фото'),
        ),
    ]
