# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_auto_20180715_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='latitude',
            field=models.FloatField(default=1, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='longitude',
            field=models.FloatField(default=1, verbose_name='Долгота'),
            preserve_default=False,
        ),
    ]
