# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0007_auto_20180715_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(default='default.JPG', upload_to='complaints/', verbose_name='Фото'),
        ),
    ]
