# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0008_auto_20180715_0222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'Заявка на ремонт дороги', 'verbose_name_plural': 'Заявки на ремонт дороги'},
        ),
    ]
