# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('description', models.CharField(max_length=256, verbose_name='Описание')),
                ('photo', models.ImageField(default='default.JPG', upload_to='complaints/', verbose_name='Фото')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'обрабатывается'), (2, 'закрыт')], default=1, verbose_name='Статус')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
