# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackrecorder', '0002_auto_20180719_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadtreck',
            name='accselerometer_points',
        ),
        migrations.RemoveField(
            model_name='roadtreck',
            name='magnetometer_points',
        ),
    ]
