# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 07:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackrecorder', '0003_auto_20180719_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadtreck',
            name='accselerometer_points',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadtreck',
            name='magnetometer_points',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
