# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trackrecorder', '0004_auto_20180719_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadtreck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
