# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MicroArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude_left', models.FloatField(help_text='левый нижний угол квадрата', verbose_name='Широта')),
                ('longitude_left', models.FloatField(help_text='левый нижний угол квадрата', verbose_name='Долгота')),
                ('latitude_right', models.FloatField(help_text='правый нижний угол', verbose_name='Широта')),
                ('longitude_right', models.FloatField(help_text='правый нижний угол', verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Участок города',
                'verbose_name_plural': 'Участки города',
            },
        ),
    ]
