# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='microarea',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'низкий'), (2, 'средний'), (3, 'высокий'), (4, 'нет')], default=4, verbose_name='Уровень опасности участка'),
        ),
    ]
