# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('number_of_jolting', models.PositiveIntegerField(verbose_name='Количество толчков')),
                ('speed', models.FloatField(verbose_name='Скорость')),
            ],
            options={
                'verbose_name': 'Сигнал неровности дороги',
                'verbose_name_plural': 'Сигналы неровности дороги',
            },
        ),
    ]
